// AN INDEX IS NOT A PLACE — the audit's coordinates, and the refusal.
//
// The audit's sample lists (`selfMarkAt`, `reservedAt`, `oneWayAt`,
// `cancellingAt`) are FLAT SUB-TILE INDICES, and until 2026-09-06 the messages
// composed from them said "first at index 1417". A person looking at the map
// cannot turn 1417 into a cell. Booked as
// docs/reviews/2026-09-04-loops-two-way-mark.md §8 row 4, which asks for every
// class at once.
//
// ═══ WHAT THESE ROWS ARE FOR, AND WHY THEY ARE SHAPED THIS WAY ═══
//
// 1. NOTHING HERE TYPES THE SUB-TILE-PER-CELL RATIO. Every expectation about
//    where a cell's indices land is generated by `cellTileIndices` /
//    `cellCrossoverIndices` — the forward direction the paint path itself uses
//    — and the decode is asserted to be its inverse. A test that typed `2` (or
//    `4`) would agree with a wrong constant. The audit's own docblock mentions
//    "all four sub-tiles" and that phrase is prose: `CELL_SUBTILE_COLS` and
//    `CELL_SUBTILE_ROWS` in collision-cell.ts are the source, and the ratio is
//    read from them here.
//
// 2. THE REFUSAL GETS ITS OWN ROWS, and they are the interesting half. The
//    defect this feature could introduce is not a coordinate that is off by
//    one; it is a coordinate INVENTED when nothing was known - cell (0,0) next
//    to a real defect, which is worse than the index it replaced. So the
//    no-stride rows assert that no cell is named at all, not merely that some
//    flag is false.

import { describe, it, expect } from 'vitest';
import {
  auditCrossovers, crossoverAuditMessage, crossoverLocus, crossoverLocusAt,
  formatCrossoverLocus,
} from '../../src/core/collision/crossover-audit';
import {
  CELL_SUBTILE_COLS, CELL_SUBTILE_ROWS, cellTileIndices, cellCrossoverIndices,
  spanForTileCol,
} from '../../src/core/collision/collision-cell';
import { withCrossover } from '../../src/core/collision/layer-transition';
import { packCollisionCell } from '../../src/core/collision/collision-cell-word';
import { SECTION_TILES_WIDE } from '../../src/core/model/s4-types';

const SOLID = packCollisionCell({ shape: 0x11, xFlip: false, yFlip: false, solidity: 'all' });
const HAND_A = withCrossover(SOLID, 'to-b');   // plane A: go to B
const HAND_B = withCrossover(SOLID, 'to-a');   // plane B: go to A
const SELF_A = withCrossover(SOLID, 'to-a');   // on plane A: rule R2 refuses it
const RESERVED = SOLID | (3 << 14);

/** A section-shaped pair of planes, but only as tall as a test needs. The
 *  STRIDE is the real one: a coordinate is a claim about the row width the
 *  editor and the bake agree on, and shrinking it would make these rows agree
 *  with a wrong width. */
const W = SECTION_TILES_WIDE;
/** Sub-tile rows the fixtures span. ⚠ A WRITE PAST A TypedArray'S END IS
 *  SILENTLY DROPPED, and the audit of an all-zero plane says nothing at all, so
 *  a fixture that is too short reads as "the message lost the coordinate". It
 *  did exactly that while these rows were being written. `put` below is the
 *  guard; this number is only how much room it has. */
const ROWS = 16;
const blank = () => new Uint16Array(W * ROWS);

/** Write a word at a sub-tile index, refusing to be a no-op. */
const put = (plane: Uint16Array, index: number, word: number): void => {
  if (index >= plane.length) throw new Error(`fixture too short: index ${index} of ${plane.length}`);
  plane[index] = word;
};

describe('crossoverLocus: the decode is the inverse of the paint path', () => {
  it('sends every sub-tile of a cell back to that cell, at any cell in the grid', () => {
    // The cells are arbitrary but SPREAD: (0,0) would pass under an
    // implementation that ignores the stride entirely.
    for (const [cc, cr] of [[0, 0], [1, 0], [12, 3], [63, 7], [127, 5]]) {
      const indices = cellTileIndices(cc, cr, W);
      expect(indices).toHaveLength(CELL_SUBTILE_COLS * CELL_SUBTILE_ROWS);
      for (const i of indices) {
        const l = crossoverLocus(i, W);
        expect(l, `index ${i}`).not.toBeNull();
        expect([l!.cellCol, l!.cellRow], `index ${i}`).toEqual([cc, cr]);
      }
    }
  });

  it('names the same half the map brush aims at, for every column of a row', () => {
    // ⚠ NOT A REIMPLEMENTATION OF THE PARITY. `spanForTileCol` is the one rule
    // that turns the 8px column under the cursor into a mark width; the locus
    // must agree with THAT function, so that is what this compares against. A
    // row asserting `col % 2` would be a second definition of the same rule and
    // would pass with both of them wrong.
    for (let col = 0; col < W; col++) {
      expect(crossoverLocus(col, W)!.half).toBe(spanForTileCol(col));
    }
  });

  it('agrees with the mark-width expander about which sub-tiles a half covers', () => {
    for (const span of ['left', 'right'] as const) {
      for (const i of cellCrossoverIndices(12, 3, W, span)) {
        const l = crossoverLocus(i, W)!;
        expect(l.half).toBe(span);
        expect([l.cellCol, l.cellRow]).toEqual([12, 3]);
      }
    }
  });

  it('reports the 8px column aeon\'s bake error names, derived not typed', () => {
    for (const [cc, cr] of [[0, 0], [12, 3], [100, 6]]) {
      for (const i of cellTileIndices(cc, cr, W)) {
        const l = crossoverLocus(i, W)!;
        const offset = l.half === 'left' ? 0 : CELL_SUBTILE_COLS - 1;
        expect(l.subCol).toBe(cc * CELL_SUBTILE_COLS + offset);
        expect(l.subRow).toBe(cr * CELL_SUBTILE_ROWS + (l.rowHalf === 'top' ? 0 : CELL_SUBTILE_ROWS - 1));
      }
    }
  });

  it('separates the row aeon\'s bake reads from the one it does not', () => {
    // aeon `tools/ojz_strip_gen.py` `apply_editor_collision_overlay` at
    // origin/master 290f4aa8: `o = (cr * 2) * W + col  # top tile row of the
    // 16px cell`. So exactly the first row of each cell is baked, and the rest
    // is authored-and-dropped. Derived from the expander's ORDER contract
    // (top-left, top-right, bottom-left, bottom-right), not from a typed 2.
    const indices = cellTileIndices(9, 4, W);
    const top = indices.slice(0, CELL_SUBTILE_COLS);
    const rest = indices.slice(CELL_SUBTILE_COLS);
    for (const i of top) expect(crossoverLocus(i, W)!.rowHalf).toBe('top');
    for (const i of rest) expect(crossoverLocus(i, W)!.rowHalf).toBe('bottom');
  });

  it('carries the section it was given and never invents one', () => {
    expect(crossoverLocus(0, W, 7)!.section).toBe(7);
    expect(crossoverLocus(0, W)!.section).toBeNull();
    expect(crossoverLocus(0, W, null)!.section).toBeNull();
    // Section 0 is a real section and must not read as "unknown".
    expect(crossoverLocus(0, W, 0)!.section).toBe(0);
  });
});

describe('crossoverLocus: what it refuses rather than guesses', () => {
  it('returns null without a stride, instead of a cell', () => {
    expect(crossoverLocus(1417, undefined)).toBeNull();
    expect(crossoverLocus(1417, null)).toBeNull();
    expect(crossoverLocus(1417, 0)).toBeNull();
    expect(crossoverLocus(1417, -1)).toBeNull();
  });

  it('refuses a stride that is not a whole number of columns', () => {
    // A fractional stride would decode to a fractional column and then be
    // floored into a cell that does not exist. There is no honest answer, so
    // there is no answer.
    expect(crossoverLocus(1417, 2.5)).toBeNull();
    expect(crossoverLocus(1417, Number.NaN)).toBeNull();
    expect(crossoverLocus(1417, Number.POSITIVE_INFINITY)).toBeNull();
  });

  it('refuses an index that is not one', () => {
    expect(crossoverLocus(-1, W)).toBeNull();
    expect(crossoverLocus(1.5, W)).toBeNull();
  });

  it('formats the refusal so the index survives and no cell is named', () => {
    const text = formatCrossoverLocus(null, 1417);
    expect(text).toContain('1417');
    expect(text).toMatch(/NO CELL COORDINATE/);
    expect(text).not.toMatch(/cell \(col/);
  });
});

describe('auditCrossovers: the record carries what a coordinate needs', () => {
  it('keeps the stride and the section it ran with', () => {
    const a = auditCrossovers(blank(), blank(), W, 5);
    expect(a.stride).toBe(W);
    expect(a.section).toBe(5);
  });

  it('records a null stride, and the cancellation scan agrees with it', () => {
    const a = auditCrossovers(blank(), blank());
    expect(a.stride).toBeNull();
    expect(a.cancellingMeasured).toBe(false);
    // ONE VALIDATION, NOT TWO. A fractional stride must not measure one and
    // refuse the other, which is what two separate gates would eventually do.
    const frac = auditCrossovers(blank(), blank(), 2.5);
    expect(frac.stride).toBeNull();
    expect(frac.cancellingMeasured).toBe(false);
  });

  it('places its own sample indices through the stride it ran with', () => {
    const a = blank(), b = blank();
    const [tl] = cellTileIndices(12, 3, W);
    put(a, tl!, SELF_A);
    const audit = auditCrossovers(a, b, W, 5);
    expect(audit.selfMarkAt).toEqual([tl]);
    const l = crossoverLocusAt(audit, audit.selfMarkAt[0]!)!;
    expect([l.section, l.cellCol, l.cellRow]).toEqual([5, 12, 3]);
  });
});

describe('crossoverAuditMessage: every class names a place, or says it cannot', () => {
  /** Put `word` on plane A at one cell's top-left sub-tile and audit it. */
  const atCell = (word: number, cc: number, cr: number, stride?: number, section?: number) => {
    const a = blank(), b = blank();
    const [tl] = cellTileIndices(cc, cr, W);
    put(a, tl!, word);
    return crossoverAuditMessage(auditCrossovers(a, b, stride, section)) ?? '';
  };

  it('names the cell for a RESERVED word', () => {
    expect(atCell(RESERVED, 12, 3, W, 5))
      .toContain('section 5, cell (col 12, row 3), left half');
  });

  it('names the cell for a SELF-MARK', () => {
    expect(atCell(SELF_A, 40, 6, W, 2))
      .toContain('section 2, cell (col 40, row 6), left half');
  });

  it('names the cell for a ONE-WAY crossover', () => {
    expect(atCell(HAND_A, 63, 7, W, 0))
      .toContain('section 0, cell (col 63, row 7), left half');
  });

  it('names the cell for a CANCELLING two-way pair', () => {
    // The fixture is the defect itself: a pair painted at the DEFAULT mark
    // width, so it spans both 8px trigger columns of the cell and nets to
    // nothing. Built through `cellTileIndices`, which is what the cell-width
    // brush writes.
    const a = blank(), b = blank();
    for (const i of cellTileIndices(20, 2, W)) { put(a, i, HAND_A); put(b, i, HAND_B); }
    const audit = auditCrossovers(a, b, W, 3);
    expect(audit.cancelling).toBe(1);
    const text = crossoverAuditMessage(audit) ?? '';
    expect(text).toMatch(/NETS TO NOTHING \(first at section 3, cell \(col 20, row 2\), left half/);
  });

  it('says a mark is on the sub-tile row the bake never reads', () => {
    const a = blank(), b = blank();
    const indices = cellTileIndices(9, 4, W);
    put(a, indices[CELL_SUBTILE_COLS]!, SELF_A);   // first sub-tile of the next row down
    const text = crossoverAuditMessage(auditCrossovers(a, b, W, 1)) ?? '';
    expect(text).toContain('cell (col 9, row 4)');
    expect(text).toMatch(/BOTTOM sub-tile row/);
  });

  it('leaves the section out rather than inventing one when it was not given', () => {
    const text = atCell(SELF_A, 12, 3, W);
    expect(text).toContain('cell (col 12, row 3)');
    expect(text).not.toMatch(/section \d/);
  });

  it('⚠ NAMES NO CELL AT ALL WITHOUT A STRIDE, and says so in words', () => {
    // THE ROW THIS WHOLE FEATURE IS AT RISK OF FAILING. A helper that fell back
    // to stride 0, or to `SECTION_TILES_WIDE` as a default, would print a
    // confident cell beside a real defect. So this asserts the ABSENCE of a
    // coordinate, not the presence of a flag.
    const text = atCell(SELF_A, 12, 3);
    expect(text).toMatch(/NO CELL COORDINATE/);
    expect(text).not.toMatch(/cell \(col/);
    expect(text).not.toMatch(/left half|right half/);
    expect(text).toMatch(/without a row stride/);
    // and the index is still there, because that is all it honestly knows
    expect(text).toContain(String(cellTileIndices(12, 3, W)[0]));
  });

  it('does not print the no-coordinate note when there is nothing to place', () => {
    // A pair with no stride already has its own "cancellation check did NOT
    // run" sentence; adding a second refusal about coordinates that no line
    // needed would train a reader to skip both.
    const a = blank(), b = blank();
    const [tl] = cellTileIndices(5, 5, W);
    put(a, tl!, HAND_A); put(b, tl!, HAND_B);
    const text = crossoverAuditMessage(auditCrossovers(a, b)) ?? '';
    expect(text).toMatch(/cancellation check did NOT run/);
    expect(text).not.toMatch(/No cell coordinates above/);
  });
});
