#!/usr/bin/env node
// Generate Aurora's CSS theme from the Empyrean design tokens (the suite's
// single source of truth). One file in → CSS custom properties out, per the
// visual contract (megaforge/design/README.md: "Aurora/Seraph emit CSS
// variables"). Aurora's accent is emerald; everything else is the shared base.
//
//   node scripts/gen-theme.mjs
//
// Token source resolution: $EMPYREAN_TOKENS, else the sibling contract repo
// (../megaforge/design/tokens.json). Output is checked in so the build never
// depends on the contract repo being present — regeneration does.

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';

const TOOL = 'aurora';
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const tokensPath = process.env.EMPYREAN_TOKENS
  || resolve(repoRoot, '..', 'megaforge', 'design', 'tokens.json');
const outPath = join(repoRoot, 'src', 'renderer', 'styles', 'theme.css');

const tokens = JSON.parse(readFileSync(tokensPath, 'utf8'));

const lines = [];
const push = (s = '') => lines.push(s);
const kebab = (s) => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

push(`/* GENERATED by scripts/gen-theme.mjs from ${process.env.EMPYREAN_TOKENS ? '$EMPYREAN_TOKENS' : 'megaforge/design/tokens.json'}`);
push(` * Source of truth: the Empyrean visual contract. Do not edit by hand — run \`npm run gen:theme\`.`);
push(` * Tool: ${TOOL} (accent: ${tokens.color.accent[TOOL].hue} ${tokens.color.accent[TOOL].value}) */`);
push(':root {');

push('  /* base surfaces */');
for (const [k, v] of Object.entries(tokens.color.base)) push(`  --${kebab(k)}: ${v};`);

push('  /* text ramp */');
for (const [k, v] of Object.entries(tokens.color.text)) push(`  --text-${k}: ${v};`);

push('  /* accent — Aurora is emerald; the suite + sibling accents are exposed too */');
push(`  --accent: ${tokens.color.accent[TOOL].value};`);
for (const [k, v] of Object.entries(tokens.color.accent)) push(`  --accent-${k}: ${v.value};`);

push('  /* semantic */');
for (const [k, v] of Object.entries(tokens.color.semantic)) push(`  --${k}: ${v};`);

push('  /* type */');
push(`  --font-ui: ${tokens.type.font.ui};`);
push(`  --font-mono: ${tokens.type.font.mono};`);
for (const [k, v] of Object.entries(tokens.type.scale)) {
  push(`  --text-${k}-size: ${v.size};`);
  push(`  --text-${k}-line: ${v.line};`);
}
for (const [k, v] of Object.entries(tokens.type.weight)) push(`  --weight-${k}: ${v};`);

push('  /* spacing */');
for (const [k, v] of Object.entries(tokens.space)) push(`  --space-${k}: ${v};`);

push('  /* radius */');
for (const [k, v] of Object.entries(tokens.radius)) push(`  --radius-${k}: ${v};`);

push('}');
push('');

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'));
console.log(`[gen-theme] ${tokensPath}\n        → ${outPath} (${lines.length} lines)`);
