import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { peerRepo, resolveRev, isAncestor } from '../support/peer-repo';
import { siblingRoot } from '../support/sibling-root.mjs';
import { verticalBandDocument } from '../support/vertical-band';
import {
  documentBands, shiftedPhaseBanks,
} from '../../src/core/formats/bg-override/bg-anim-band';
import { serializeBgOverride } from '../../src/core/formats/bg-override/bg-override';

/**
 * THE BAKE PROOF — Aurora's vertical band, through AEON'S OWN GUARD.
 *
 * Every other row in this parcel is Aurora asserting about Aurora. This one
 * hands bytes that Aurora's promote door actually produced to
 * `tools/inject_editor_bg.py` — its `band_axis_geometry`, its
 * `validate_band_phase_axis`, AND its `main()`, which is the real emitter that
 * writes the 44-byte band record the engine reads — executed, at a committed
 * aeon revision.
 *
 * ═══ HOW IT REACHES AEON, AND THE TWO RULES IT KEEPS ═══
 *
 *   NEVER THROUGH THE SIBLING WORKING TREE. `../aeon` is another lane's live
 *   checkout and may be mid-edit; a run that imported from it would measure
 *   somebody's unsaved afternoon. The tools are MATERIALISED with `git archive`
 *   at the pinned commit into a temp directory this test owns, and nothing is
 *   ever written under the aeon checkout.
 *
 *   THE PIN IS NAMED AND ITS CURRENCY IS CHECKED. `AXIS_REV` is the revision the
 *   vendored contract's `amendments[0]` records. A pin that has left aeon's
 *   published history is drift of the loudest kind and FAILS rather than skips.
 *
 * ═══ THE CONTROL IS THE POINT ═══
 *
 * A green "aeon admitted our band" proves nothing on its own: aeon admits
 * almost everything, deliberately (composites are legal on both axes). What
 * makes it evidence is the PAIR — the same band, same geometry, same `axis`,
 * with its phases regenerated by the HORIZONTAL arm, must be REFUSED by name.
 * That is the exact accident aeon's guard was written for (a horizontal-only
 * shift-fill run over a band declared vertical), it is reachable from this
 * repo's own code, and it is constructed here from the same source art. If the
 * refusal arm ever goes green, the guard is not running and the admission arm
 * is worthless — which is why they are in one file and neither is skipped
 * without the other.
 *
 * ═══ WHAT THIS DOES NOT PROVE ═══
 *
 * That a band moves vertically ON SCREEN. That needs a built ROM in an emulator
 * and is the overseer's, in the foreground. The ceiling here is: correct bytes,
 * through aeon's own guard, at a pinned revision.
 */

/** The revision the vendored contract's axis amendment was read at. */
const AXIS_REV = '3a4712faa920100653669c1ec3fc26c2da71ef68';
/** The branch whose tip answers "is the pin still in aeon's history?". */
const AEON_TIP = 'origin/master';

/**
  * What the emitter needs, and nothing more: the tools, the project.json they
  * read act ids from, and the two per-game TOMLs `vram_map`/`bganim_room` read
  * the tile capacity and the section ceiling out of. The act's own `data/`
  * directory is NOT extracted — this test supplies the override document
  * itself, which is the whole point.
  */
const ARCHIVE_PATHS = [
  'tools', 'project.json', 'games/sonic4/vram.toml', 'games/sonic4/map.toml',
];

const aeon = peerRepo('aeon');
let work: string | null = null;
let setupWhy = '';

function python(): string | null {
  return spawnSync('python3', ['--version']).status === 0 ? 'python3' : null;
}

beforeAll(() => {
  if (aeon === null) { setupWhy = 'no aeon checkout beside this repo (set AEON_DIR)'; return; }
  if (resolveRev(aeon, AXIS_REV) === null) {
    setupWhy = `aeon ${AXIS_REV} does not resolve in ${aeon} (fetch it)`; return;
  }
  if (python() === null) { setupWhy = 'no python3 on PATH'; return; }
  const dir = mkdtempSync(join(tmpdir(), 'aurora-aeon-axis-'));
  // `git archive | tar -x` — a READ of aeon's object database into a directory
  // this test owns. The aeon checkout is never written to and never imported
  // from by path.
  const tar = execFileSync('git', ['-C', aeon, 'archive', AXIS_REV, ...ARCHIVE_PATHS],
    { maxBuffer: 1 << 28, encoding: 'buffer' });
  const untar = spawnSync('tar', ['-x', '-C', dir], { input: tar });
  if (untar.status !== 0) {
    setupWhy = `could not extract aeon ${AXIS_REV}: ${String(untar.stderr)}`;
    rmSync(dir, { recursive: true, force: true });
    return;
  }
  // The emitter writes its four outputs into the act's generated directory and
  // does not create it. Ours, inside the work dir — aeon's tree is never touched.
  mkdirSync(join(dir, 'games', 'sonic4', 'data', 'generated', 'ojz', 'act1'), { recursive: true });
  if (!existsSync(join(dir, 'tools', 'inject_editor_bg.py'))) {
    setupWhy = `aeon ${AXIS_REV} has no tools/inject_editor_bg.py`;
    rmSync(dir, { recursive: true, force: true });
    return;
  }
  work = dir;
});

afterAll(() => { if (work !== null) rmSync(work, { recursive: true, force: true }); });

/** The one probe script. Written into the work dir so nothing is executed from aeon's tree. */
const PROBE = `
import json, os, shutil, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tools'))
import inject_editor_bg as ib
doc_path = sys.argv[1]
anims = json.load(open(doc_path))['anims']
out = {'axes': list(ib.BAND_AXES), 'geometry': [], 'guard': 'admitted', 'why': '',
       'emitted': None, 'emp': '', 'banks_bytes': 0}
try:
    for i, a in enumerate(anims):
        axis, unit_bytes, unit_shift, period_px = ib.band_axis_geometry(a, where='band %d' % i)
        out['geometry'].append({'axis': axis, 'unit_bytes': unit_bytes,
                                'unit_shift': unit_shift, 'period_px': period_px,
                                'pattern_px': a['pattern_px']})
        assert a['pattern_px'] == period_px, (
            'band %d: pattern_px %d is not the period along %s (%d)'
            % (i, a['pattern_px'], axis, period_px))
    ib.validate_band_phase_axis(anims)
    # THE EMITTER ITSELF, not a re-implementation of it. main() reads the
    # override at its own hardcoded path and writes the four generated files;
    # the 44-byte record it emits is what the engine reads at runtime.
    shutil.copyfile(doc_path, ib.OVERRIDE)
    ib.main()
    emp = open(os.path.join(ib.OUT_DIR, 'bg_anim.emp')).read()
    out['emp'] = emp
    out['banks_bytes'] = os.path.getsize(os.path.join(ib.OUT_DIR, 'bg_anim_banks.bin'))
    for line in emp.splitlines():
        if line.startswith('data _BgAnim_Band0_hdr'):
            fields = line.split('=', 1)[1].strip().strip('[]').split(',')
            keys = ['driver', 'rate_shift', 'step_mask', 'col_shift', 'tile_count', 'vram_dest']
            out['emitted'] = dict(zip(keys, [f.strip() for f in fields]))
except AssertionError as e:
    out['guard'] = 'refused'
    out['why'] = str(e)
print(json.dumps(out))
`;

interface Probe {
  axes: string[];
  geometry: Array<{ axis: string; unit_bytes: number; unit_shift: number;
                    period_px: number; pattern_px: number }>;
  guard: 'admitted' | 'refused';
  why: string;
  /** The 44-byte record's six header fields, as the emitter spelled them. */
  emitted: Record<string, string> | null;
  emp: string;
  banks_bytes: number;
}

function runAeonGuard(doc: unknown): Probe {
  if (work === null) throw new Error('the aeon work tree was not materialised');
  const probePath = join(work, 'aurora_axis_probe.py');
  writeFileSync(probePath, PROBE);
  const docPath = join(work, 'aurora_doc.json');
  writeFileSync(docPath, serializeBgOverride(doc as never));
  const r = spawnSync('python3', [probePath, docPath], {
    cwd: work,
    encoding: 'utf8',
    // aeon's tool chain resolves its own peers through the suite root. Pointed
    // at the REAL suite root deliberately: it is only ever read from, and a
    // stand-in would make the import fail for a reason unrelated to the axis.
    env: { ...process.env, EMPYREAN_SUITE_ROOT: siblingRoot() ?? '' },
  });
  if (r.status !== 0) {
    throw new Error(`aeon probe failed (${r.status}):\n${r.stderr}\n${r.stdout}`);
  }
  return JSON.parse(r.stdout.trim().split('\n').pop()!) as Probe;
}

/** Skip loudly, in the one shape this repo's skip-report accepts. */
function skipUnlessReady(ctx: { skip: (why: string) => void }): boolean {
  if (work !== null) return false;
  ctx.skip(`SKIPPED, NOT PASSED: NOTHING WAS MEASURED against aeon: ${setupWhy}. `
    + `This row runs aeon ${AXIS_REV}'s own axis guard against bytes Aurora wrote; `
    + 'without it the vertical band is proven only by Aurora asserting about Aurora.');
  return true;
}

describe('the pin this parcel was built against is still aeon history', () => {
  it(`aeon ${AXIS_REV.slice(0, 8)} is reachable from ${AEON_TIP}`, (ctx) => {
    if (aeon === null) {
      ctx.skip(`SKIPPED, NOT PASSED: no aeon checkout beside this repo (set AEON_DIR), so `
        + `CANNOT MEASURE whether ${AXIS_REV} is still in aeon's published history`);
      return;
    }
    const tip = resolveRev(aeon, AEON_TIP);
    if (tip === null) {
      ctx.skip(`SKIPPED, NOT PASSED: ${AEON_TIP} does not resolve in ${aeon}, so `
        + `CANNOT MEASURE the currency of pin ${AXIS_REV}`);
      return;
    }
    // NOT a skip: the ref resolved, so this WAS measured. A pin that has left
    // aeon's history means the axis contract this repo transcribed was rebased
    // or reverted, and every derivation in this parcel needs re-reading.
    expect(
      isAncestor(aeon, AXIS_REV, tip),
      `NOT AN AURORA REGRESSION IN ITSELF: aeon ${AXIS_REV} is no longer an ancestor of `
      + `${AEON_TIP} (${tip}). The motion-axis contract Aurora transcribed came from that `
      + 'commit; re-read tools/EFFECTS_CONSUMER_CONTRACT.md §1.2 and tools/inject_editor_bg.py '
      + 'at the new tip before trusting anything in bg-anim-band-axis.test.ts.',
    ).toBe(true);
  });
});

describe('AEON\'S OWN GUARD, run against bytes Aurora wrote', () => {
  it('the guard is present at the pin and knows both axes', (ctx) => {
    if (skipUnlessReady(ctx)) return;
    const probe = runAeonGuard(verticalBandDocument());
    // ANTI-VACUOUS: if `BAND_AXES` came back with one entry, or the probe had
    // silently imported some other module, every assertion below would be about
    // nothing. This is the row that says the guard we ran is the axis guard.
    expect(probe.axes).toEqual(['horizontal', 'vertical']);
  });

  it('derives our vertical band\'s unit from COLS and its period from ROWS', (ctx) => {
    if (skipUnlessReady(ctx)) return;
    const doc = verticalBandDocument();
    const band = documentBands(doc)[0];
    const probe = runAeonGuard(doc);
    expect(probe.geometry).toHaveLength(1);
    const g = probe.geometry[0];
    expect(g.axis).toBe('vertical');
    // aeon's own numbers, compared against the geometry Aurora authored — and
    // both are DERIVED here rather than pinned, so a swap on either side shows.
    expect(g.unit_bytes).toBe(band.cols * 32);
    expect(1 << g.unit_shift).toBe(g.unit_bytes);
    expect(g.period_px).toBe(band.rows * 8);
    expect(g.pattern_px).toBe(g.period_px);
    // The horizontal reading of the SAME geometry, asserted as NOT what aeon
    // derived: on a 4x8 band the two readings differ in both numbers, so this
    // pair is what makes `axis` observable rather than decorative.
    expect(g.unit_bytes).not.toBe(band.rows * 32);
    expect(g.period_px).not.toBe(band.cols * 8);
  });

  it('ADMITS the band Aurora\'s column-wise shift-fill produced', (ctx) => {
    if (skipUnlessReady(ctx)) return;
    const probe = runAeonGuard(verticalBandDocument());
    expect(probe.guard, `aeon refused Aurora's own vertical band: ${probe.why}`)
      .toBe('admitted');
  });

  /**
   * THE RED ARM, IN THE SAME RUN. Without it the row above is "aeon admitted
   * something", which aeon does for almost everything on purpose.
   */
  it('REFUSES the same band with HORIZONTALLY-filled phases: the accident the guard is for', (ctx) => {
    if (skipUnlessReady(ctx)) return;
    const doc = verticalBandDocument();
    const band = documentBands(doc)[0];
    // The one thing this repo could no longer do through its own API: run the
    // horizontal arm over a vertical band. Constructed by hand precisely
    // because `shiftedPhaseBanks` reads the axis off the band and cannot be
    // asked for the other arm — so this is the shape of a document Aurora would
    // have written BEFORE this parcel, kept as the control for it.
    band.phases = shiftedPhaseBanks({ ...band, axis: 'horizontal' }, band.phases[0]);
    const probe = runAeonGuard(doc);
    expect(probe.guard,
      'aeon ADMITTED a vertical band whose phases are horizontal translations. Either the '
      + 'guard is not running in this probe (which would make the admission row above '
      + 'vacuous) or the fixture art is uniform along one axis, where the two rolls coincide '
      + 'and aeon admits the band deliberately.').toBe('refused');
    expect(probe.why).toMatch(/declares axis "vertical"/);
    expect(probe.why).toMatch(/exact HORIZONTAL/);
  });

  /**
   * THE BAKE, one step past the guard: aeon's own `main()` turns our document
   * into the four generated files, and the 44-byte record it writes is what
   * `BgAnim_Update` reads. Two of its six fields are the axis — `step_mask` is
   * the period along it and `col_shift` is log2 of the rotation unit — so this
   * is where the axis stops being a JSON key and becomes bytes.
   */
  it('EMITS a record whose step_mask and col_shift are the VERTICAL readings', (ctx) => {
    if (skipUnlessReady(ctx)) return;
    const doc = verticalBandDocument();
    const band = documentBands(doc)[0];
    const probe = runAeonGuard(doc);
    expect(probe.emitted, `aeon emitted no band record:\n${probe.emp}`).not.toBeNull();
    const rec = probe.emitted!;
    // Every expectation DERIVED from the band Aurora authored, never copied out
    // of the emitter's output.
    expect(Number(rec.step_mask)).toBe(band.rows * 8 - 1);
    expect(1 << Number(rec.col_shift)).toBe(band.cols * 32);
    expect(Number(rec.tile_count)).toBe(band.cols * band.rows);
    // The horizontal readings of the SAME geometry, asserted as NOT emitted.
    // Without this pair a 4x4 band would satisfy both and prove nothing.
    expect(Number(rec.step_mask)).not.toBe(band.cols * 8 - 1);
    expect(1 << Number(rec.col_shift)).not.toBe(band.rows * 32);
    // The banks blob is the real art: 8 banks x n slots x 32 bytes.
    expect(probe.banks_bytes).toBe(8 * band.cols * band.rows * 32);
    // The record cannot carry the axis — `col_shift` and `step_mask` are units —
    // so the emitter names it in the comment, which is the only place a reader
    // of the generated module can find it.
    expect(probe.emp).toMatch(/vertical \(scrolls up\)/);
  });

  it('leaves a HORIZONTAL band with the same art alone', (ctx) => {
    if (skipUnlessReady(ctx)) return;
    // The other control: the guard must be narrow. A band that claims horizontal
    // and is filled horizontally is the shipped case, and refusing it would be a
    // guard that stops the product rather than one that catches the accident.
    const doc = verticalBandDocument();
    const band = documentBands(doc)[0];
    band.axis = 'horizontal';
    band.pattern_px = band.cols * 8;
    band.phases = shiftedPhaseBanks({ ...band, axis: 'horizontal' }, band.phases[0]);
    const probe = runAeonGuard(doc);
    expect(probe.guard, probe.why).toBe('admitted');
    expect(probe.geometry[0].axis).toBe('horizontal');
    expect(probe.geometry[0].unit_bytes).toBe(band.rows * 32);
    // ...and the SAME emitter, on the SAME art, writes the OTHER two numbers.
    // This is the pair that makes the record's two axis fields observable: one
    // band, one geometry, two records, differing exactly where the axis says.
    expect(Number(probe.emitted!.step_mask)).toBe(band.cols * 8 - 1);
    expect(1 << Number(probe.emitted!.col_shift)).toBe(band.rows * 32);
    expect(probe.emp).toMatch(/horizontal \(scrolls left\)/);
  });
});
